import { expect, test } from "bun:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { envCheck } from "./env-check.ts";

test("env-check reports names but not values",async()=>{const d=await mkdtemp(path.join(tmpdir(),'sightr-'));await writeFile(path.join(d,'.env'),'PUBLIC=yes\nBROKEN secret-value\nSECRET=s3cret-value\n');const oldOut=console.log,oldErr=console.error;let out='',err='';console.log=(...x)=>{out+=x.join(' ') };console.error=(...x)=>{err+=x.join(' ')};try{expect(await envCheck({HERDR_PLUGIN_CONFIG_DIR:d,PATH:''},async()=>({code:0,stdout:'',stderr:''}))).toBe(0);}finally{console.log=oldOut;console.error=oldErr}expect(out).toContain(d);expect(out).toContain('PUBLIC');expect(out).not.toContain('s3cret-value');expect(err).toContain('malformed');expect(err).not.toContain('secret-value');});
test("absent .env exits successfully",async()=>{const d=await mkdtemp(path.join(tmpdir(),'sightr-')); let out=''; const old=console.log; console.log=(...x)=>{out+=x.join(' ')}; try { expect(await envCheck({HERDR_PLUGIN_CONFIG_DIR:d,PATH:''},async()=>({code:0,stdout:'',stderr:''}))).toBe(0); } finally { console.log=old; } expect(out).toContain('exists: no'); expect(out).toContain('keys: (none)'); });
test("warns on a pre-1.0 SIGHTER_ key and names the rewrite",async()=>{const d=await mkdtemp(path.join(tmpdir(),'sightr-'));await writeFile(path.join(d,'.env'),'SIGHTER_PORT=8788\nSIGHTR_HOST=127.0.0.1\n');let err='';const old=console.error,oldOut=console.log;console.error=(...x)=>{err+=x.join(' ')};console.log=()=>{};try{expect(await envCheck({HERDR_PLUGIN_CONFIG_DIR:d,PATH:''},async()=>({code:0,stdout:'',stderr:''}))).toBe(0);}finally{console.error=old;console.log=oldOut}expect(err).toContain('SIGHTER_PORT');expect(err).toContain('rename SIGHTER_ to SIGHTR_');expect(err).not.toContain('SIGHTR_HOST');});
