import { expect, test } from "bun:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { applyUpdate, majorOf, manifestVersionFrom, nextMajorRelease, parseLsRemoteTags, refreshRegistry, releaseInMajor, update, updateCheckout, versionGt } from "./update.ts";
import type { Run, RunResult } from "./types.ts";

const remote = "a refs/tags/v0.999.0\nz refs/tags/v1.999.0\nb refs/tags/v9.10.0\nc refs/tags/v10.0.0\nd refs/tags/v10.2.0\ne refs/tags/v11.0.0";
async function root(version = "9.9.9") { const r = await mkdtemp(path.join(tmpdir(), "ctl-update-")); await writeFile(path.join(r, "herdr-plugin.toml"), `version = "${version}"\n`); return r; }
function fake(overrides: (cmd:string,args:string[]) => Partial<RunResult> = () => ({})) { const calls:{cmd:string,args:string[],opts?:any}[]=[]; const run:Run=async(cmd,args,opts)=>{calls.push({cmd,args,opts}); const extra=overrides(cmd,args); const defaultCode=cmd==="git"&&args.includes("symbolic-ref")&&args.includes("HEAD")?1:0; return {code:defaultCode,stdout:"",stderr:"",...extra};}; return {run,calls}; }
const is = (calls:{args:string[]}[], parts:string[]) => calls.some(c => c.args.join(" ") === parts.join(" "));

test("release tags accept strict versions and peeled annotated tags", () => { expect(parseLsRemoteTags("aaa refs/tags/v9.10.0\nbbb refs/tags/v9.10.0^{}\nccc refs/tags/v9.11.0-beta.1\nddd refs/tags/v9.11\neee refs/tags/nightly")).toEqual([{major:9,minor:10,patch:0,tag:"v9.10.0",commit:"bbb"}]); });
test("release selection is numeric and advances one major at a time", () => { const tags=parseLsRemoteTags("a refs/tags/v0.9.0\nb refs/tags/v0.100.1\nc refs/tags/v9.10.0\nd refs/tags/v10.0.0\ne refs/tags/v10.2.0\nf refs/tags/v11.0.0"); expect(releaseInMajor(tags,0)?.tag).toBe("v0.100.1"); expect(releaseInMajor(tags,9)?.tag).toBe("v9.10.0"); expect(nextMajorRelease(tags,9)?.tag).toBe("v10.2.0"); });
test("semver helpers handle prereleases and unreadable versions", () => { expect(versionGt("1.0.0","1.0.0-beta.5")).toBe(true); expect(versionGt("1.0.0","1.0.0")).toBe(false); expect(majorOf("unknown")).toBeUndefined(); expect(manifestVersionFrom('version = "0.92.0"')).toBe("0.92.0"); });

test("managed shallow update fetches and force-detaches the release tag", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("--is-shallow-repository")?{stdout:"true"}:c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v9.10.0"}:c==="git"&&a.includes("log")?{stdout:"abc subject"}:c==="git"&&a.includes("rev-parse")&&a.at(-1)==="HEAD"?{stdout:"old"}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(0);expect(x.calls.some(c=>c.args.includes("fetch")&&c.args.includes("--depth")&&c.args.includes("v9.10.0"))).toBe(true);expect(x.calls.some(c=>c.args.includes("checkout")&&c.args.includes("--force")&&c.args.includes("refs/tags/v9.10.0"))).toBe(true);});
test("managed full update never adds a shallow fetch", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("--is-shallow-repository")?{stdout:"false"}:c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v9.10.0"}:{});await updateCheckout([], {root:r,run:x.run});expect(is(x.calls,["-C",r,"fetch","origin","tag","v9.10.0"])).toBe(true);});
test("managed update targets a release tag, never FETCH_HEAD or pull", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v9.10.0"}:{});await updateCheckout([], {root:r,run:x.run});expect(x.calls.some(c=>c.args.includes("FETCH_HEAD")||c.args.includes("pull"))).toBe(false);});
test("empty release list refuses an unverified origin HEAD", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:""}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(1);expect(x.calls.some(c=>c.args.includes("fetch")||c.args.includes("checkout"))).toBe(false);});
test("SIGHTR_UPDATE_REF bypasses release listing", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("describe")?{stdout:"v0.29.0"}:{});expect(await updateCheckout([], {root:r,env:{SIGHTR_UPDATE_REF:"v0.29.0"},run:x.run})).toBe(0);expect(x.calls.some(c=>c.args.includes("ls-remote"))).toBe(false);});
test("already current by commit or version performs no checkout", async()=>{for(const head of ["a","different"]){const r=await root("9.10.0");const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.at(-1)==="HEAD"?{stdout:head}:{});await updateCheckout([], {root:r,run:x.run});expect(x.calls.some(c=>c.args.includes("checkout"))).toBe(false);}});
test("wrong checkout tag is rejected", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"wrong"}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(1);});
test("routine update announces a higher major without crossing it", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v9.10.0"}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(0);});
test("--major crosses exactly the next major", async()=>{const r=await root("9.10.0");const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v10.2.0"}:{});await updateCheckout(["--major"], {root:r,run:x.run});expect(x.calls.some(c=>c.args.includes("v10.2.0"))).toBe(true);expect(x.calls.some(c=>c.args.includes("v11.0.0"))).toBe(false);});
test("--major with no higher release is a no-op", async()=>{const r=await root("9.10.0");const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:"a refs/tags/v9.10.0"}:{});expect(await updateCheckout(["--major"],{root:r,run:x.run})).toBe(0);expect(x.calls.some(c=>c.args.includes("checkout"))).toBe(false);});
test("unreadable manifest pins the newest release tag", async()=>{const r=await root();await writeFile(path.join(r,"herdr-plugin.toml"),"not a manifest\n");const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v11.0.0"}:{});await updateCheckout([], {root:r,run:x.run});expect(x.calls.some(c=>c.args.includes("v11.0.0"))).toBe(true);});
test("linked checkout pulls its resolved upstream when it stays in the major", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("symbolic-ref")?{code:0,stdout:"refs/heads/main"}:c==="git"&&a.includes("rev-parse")&&a.includes("@{u}")?{stdout:"origin/maint"}:c==="git"&&a.includes("show")?{stdout:'version = "9.10.0"'}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(0);expect(x.calls.some(c=>c.args.includes("pull")&&c.args.includes("--ff-only"))).toBe(true);});
test("linked major crossing refuses before pull", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("symbolic-ref")?{code:0,stdout:"refs/heads/main"}:c==="git"&&a.includes("@{u}")?{stdout:"origin/main"}:c==="git"&&a.includes("show")?{stdout:'version = "10.0.0"'}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(0);expect(x.calls.some(c=>c.args.includes("pull"))).toBe(false);});
test("linked checkout with no upstream still propagates pull failure", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("symbolic-ref")?{code:0,stdout:"refs/heads/main"}:c==="git"&&a.includes("@{u}")?{code:1}:c==="git"&&a.includes("pull")?{code:7}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(7);});
test("non-git root is refused", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("--git-dir")?{code:1}:{});expect(await updateCheckout([], {root:r,run:x.run})).toBe(1);});
test("applyUpdate orders build, restart and registry refresh and stops on build failure", async()=>{const order:string[]=[];expect(await applyUpdate({},fake().run,{build:async()=>{order.push("build");return 0},restart:async()=>{order.push("restart");return 0},refresh:async()=>{order.push("refresh")}})).toBe(0);expect(order).toEqual(["build","restart","refresh"]);order.length=0;expect(await applyUpdate({},fake().run,{build:async()=>{order.push("build");return 3},restart:async()=>{order.push("restart");return 0}})).toBe(3);expect(order).toEqual(["build"]);});
test("update children never receive parsed VAPID secrets", async()=>{const r=await root();const x=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v9.10.0"}:{});await updateCheckout([], {root:r,env:{SIGHTR_VAPID_PRIVATE:"super-secret"},run:x.run});expect(x.calls.filter(c=>c.cmd==="git").every(c=>!JSON.stringify(c.opts?.env??{}).includes("super-secret"))).toBe(true);});
test("refreshRegistry is silent when Herdr is absent", async()=>{const r=await root();const x=fake((c,_a)=>c==="herdr"?{code:127}:{});const output:string[]=[];const original=console.log;console.log=(...a:any[])=>output.push(a.join(" "));try{await refreshRegistry({root:r,run:x.run});}finally{console.log=original;}expect(output).toEqual([]);expect(x.calls.some(c=>c.args.includes("link"))).toBe(false);});
test("refreshRegistry leaves managed installs alone", async()=>{const r=await root();const x=fake((c,a)=>c==="herdr"&&a[0]==="--version"?{}:{});const output:string[]=[];const original=console.log;console.log=(...a:any[])=>output.push(a.join(" "));try{await refreshRegistry({root:r,run:x.run});}finally{console.log=original;}expect(output.join("\n")).toContain("registry left alone");expect(x.calls.some(c=>c.args.includes("link"))).toBe(false);});
test("refreshRegistry relinks linked installs and reports link failures", async()=>{for(const code of [0,1]){const r=await root();const x=fake((c,a)=>c==="herdr"&&a[0]==="--version"?{}:c==="git"&&a.includes("symbolic-ref")?{code:0}:c==="herdr"&&a.includes("link")?{code}:{});const output:string[]=[];const original=console.log;console.log=(...a:any[])=>output.push(a.join(" "));try{await refreshRegistry({root:r,run:x.run});}finally{console.log=original;}expect(x.calls.some(c=>c.cmd==="herdr"&&c.args[0]==="plugin"&&c.args[1]==="link")).toBe(true);if(code===0)expect(output.join("\n")).toContain("registry refreshed");else expect(output.join("\n")).toContain("run: herdr plugin link");}});
test("update reexecutes _apply-update once only after a successful checkout", async()=>{const success=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("describe")?{stdout:"v1.999.0"}:c!=="git"?{code:6}:{});const n=await update([],{},success.run);expect(n).toBe(6);expect(success.calls.filter(c=>c.cmd!=="git").length).toBe(1);expect(success.calls.at(-1)?.args.at(-1)).toBe("_apply-update");const failed=fake((c,a)=>c==="git"&&a.includes("ls-remote")?{stdout:remote}:c==="git"&&a.includes("checkout")?{code:5}:{});expect(await update([],{},failed.run)).toBe(5);expect(failed.calls.some(c=>c.cmd!=="git")).toBe(false);});
