import { readFile, rm } from "node:fs/promises";
import type { Run } from "./types.ts";
export type WinProc={ProcessId:number;ParentProcessId:number;CommandLine:string|null};
export function selfProcessIds(procs:WinProc[],pid:number){const out:number[]=[];let current=pid;for(let i=0;i<16&&current>0&&!out.includes(current);i++){out.push(current);const p=procs.find(x=>x.ProcessId===current);current=p?.ParentProcessId??0}return out}
export function bridgeProcesses(procs:WinProc[],o:{pluginRoot:string;vbsPath:string;selfIds:number[];listeners:number[]}){const back=`${o.pluginRoot}\\bridge\\index.ts`,fwd=`${o.pluginRoot.replace(/\\/g,"/")}/bridge/index.ts`;return procs.filter(p=>!o.selfIds.includes(p.ProcessId)&&p.CommandLine!=null).filter(p=>{const c=p.CommandLine!;return c.includes(back)||c.includes(fwd)||c.includes("_exec-bridge")||c.includes(o.vbsPath)||(o.listeners.includes(p.ProcessId)&&/\bbridge[\\/]index\.ts\b/i.test(c))})}
async function inventory(run:Run){const r=await run("powershell",["-NoProfile","-Command","Get-CimInstance Win32_Process | Select-Object ProcessId,ParentProcessId,CommandLine | ConvertTo-Json"]);if(r.code!==0)return[];try{const x=JSON.parse(r.stdout);return (Array.isArray(x)?x:[x]) as WinProc[]}catch{return[]}}
export function parseOwningPids(stdout:string):number[]{if(!stdout.trim()||stdout.trim()==="null")return[];try{const x=JSON.parse(stdout);return(Array.isArray(x)?x:[x]).map((v:any)=>Number(v.OwningProcess)).filter(Boolean)}catch{return[]}}
async function portListeners(run:Run,port:string):Promise<number[]>{const r=await run("powershell",["-NoProfile","-Command",`Get-NetTCPConnection -LocalAddress @('127.0.0.1','0.0.0.0','::','::1') -LocalPort ${port} -ErrorAction SilentlyContinue | Select-Object OwningProcess | ConvertTo-Json`]);if(r.code!==0)return[];return parseOwningPids(r.stdout)}
export async function waitPortFree(spec:{port:string},run:Run,sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms))){let pids:number[]=[];for(let i=0;i<25;i++){pids=await portListeners(run,spec.port);if(pids.length===0)return;await sleep(200)}throw new Error(`127.0.0.1:${spec.port} is still bound by pid(s) ${pids.join(", ")} after stopping Sightr's bridges. Something that is not this checkout's bridge owns the port; refusing to start a second listener beside it (#41).`)}
export async function stopAllBridges(spec:{pluginRoot:string;vbsPath:string;port:string;selfIds?:number[];processFile?:string},run:Run,sleep?: (ms:number)=>Promise<void>){if(spec.processFile)await stopRecorded({processFile:spec.processFile},spec,run);const ps=await inventory(run),ids=spec.selfIds??selfProcessIds(ps,process.pid),lr=await run("powershell",["-NoProfile","-Command",`Get-NetTCPConnection -LocalPort ${spec.port} -ErrorAction SilentlyContinue | Select-Object OwningProcess | ConvertTo-Json`]);let listeners:number[]=[];try{const x=JSON.parse(lr.stdout);listeners=(Array.isArray(x)?x:[x]).map((v:any)=>Number(v.OwningProcess)).filter(Boolean)}catch{}for(const p of bridgeProcesses(ps,{...spec,selfIds:ids,listeners}))await run("powershell",["-NoProfile","-Command",p.CommandLine?.includes("_exec-bridge")||p.CommandLine?.includes(spec.vbsPath)?`taskkill /PID ${p.ProcessId} /T /F`:`Stop-Process -Id ${p.ProcessId} -Force`]);await waitPortFree(spec,run,sleep)}
export async function stopRecorded(paths:{processFile:string},spec:{pluginRoot:string;vbsPath:string},run:Run){let raw="";try{raw=await readFile(paths.processFile,"utf8")}catch{return}const m=/^(\d+)\|(\d+)$/.exec(raw.trim());if(!m)throw new Error(`invalid Sightr process ownership state: ${raw.trim()}`);const ps=await inventory(run);for(const id of m.slice(1).map(Number)){const p=ps.find(x=>x.ProcessId===id),c=p?.CommandLine??"";if(id>0&&(c.includes(`${spec.pluginRoot}\\bridge\\index.ts`)||c.includes(`${spec.pluginRoot}/bridge/index.ts`)||c.includes("_exec-bridge")||c.includes(spec.vbsPath)))await run("powershell",["-NoProfile","-Command",`Stop-Process -Id ${id} -Force`]);}await rm(paths.processFile,{force:true})}
