import type { AgentCommand } from "./types.ts";

export const CLAUDE: readonly AgentCommand[] = [
  { command: "/compact", description: "Summarize the conversation to free up context; optional focus", takesArg: true, argHint: "[instructions]", common: true, dangerous: false },
  { command: "/clear", description: "Start a fresh conversation with empty context", takesArg: false, argHint: "", common: true, dangerous: true },
  { command: "/model", description: "Switch the model; opens a picker if no name given", takesArg: true, argHint: "[model]", common: true, dangerous: false },
  { command: "/resume", description: "Resume a previous conversation by id, name, or picker", takesArg: true, argHint: "[session]", common: true, dangerous: false },
  { command: "/init", description: "Generate a starter CLAUDE.md for this project", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/review", description: "Review a GitHub pull request by number (lists open PRs if none)", takesArg: true, argHint: "[PR]", common: true, dangerous: false },
  { command: "/status", description: "Show version, model, account, and connectivity info", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/usage", description: "Show session cost, plan limits, and activity stats", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/context", description: "Visualize context-window usage with optimization hints", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/memory", description: "Edit CLAUDE.md memory files and auto-memory entries", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/help", description: "Show help and list available commands", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/add-dir", description: "Add an extra working directory for file access", takesArg: true, argHint: "<path>", common: false, dangerous: false },
  { command: "/agents", description: "Manage subagent configurations and view running agents", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/branch", description: "Fork the conversation here to explore a different direction", takesArg: true, argHint: "[name]", common: false, dangerous: false },
  { command: "/btw", description: "Ask a quick side question without adding it to history", takesArg: true, argHint: "<question>", common: false, dangerous: false },
  { command: "/cd", description: "Move the session to a new working directory", takesArg: true, argHint: "<path>", common: false, dangerous: false },
  { command: "/code-review", description: "Review the current diff for bugs and cleanups", takesArg: true, argHint: "[level]", common: false, dangerous: false },
  { command: "/config", description: "Open settings, or set a value with key=value", takesArg: true, argHint: "[key=value]", common: false, dangerous: false },
  { command: "/copy", description: "Copy the last assistant response to the clipboard", takesArg: true, argHint: "[N]", common: false, dangerous: false },
  { command: "/cost", description: "Show token cost and usage for the current session", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/deep-research", description: "Fan out web searches and synthesize a cited report", takesArg: true, argHint: "<question>", common: false, dangerous: false },
  { command: "/diff", description: "Open an interactive viewer of uncommitted changes", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/doctor", description: "Diagnose and verify your Claude Code installation", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/effort", description: "Set the model reasoning effort level", takesArg: true, argHint: "[low|medium|high|max]", common: false, dangerous: false },
  { command: "/export", description: "Export the conversation as plain text", takesArg: true, argHint: "[filename]", common: false, dangerous: false },
  { command: "/fast", description: "Toggle fast mode on or off", takesArg: true, argHint: "[on|off]", common: false, dangerous: false },
  { command: "/feedback", description: "Submit feedback or report a bug to Anthropic", takesArg: true, argHint: "[report]", common: false, dangerous: false },
  { command: "/fork", description: "Spawn a background subagent that inherits this conversation", takesArg: true, argHint: "<directive>", common: false, dangerous: false },
  { command: "/goal", description: "Set a completion condition; keep working until it is met", takesArg: true, argHint: "[condition|clear]", common: false, dangerous: false },
  { command: "/hooks", description: "View hook configurations for tool events", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/ide", description: "Manage IDE integrations and show connection status", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/login", description: "Sign in to your Anthropic account", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/logout", description: "Sign out from your Anthropic account", takesArg: false, argHint: "", common: false, dangerous: true },
  { command: "/loop", description: "Run a prompt repeatedly on an interval (self-paced if none)", takesArg: true, argHint: "[interval] [prompt]", common: false, dangerous: false },
  { command: "/mcp", description: "Manage MCP server connections and auth", takesArg: true, argHint: "[subcommand]", common: false, dangerous: false },
  { command: "/permissions", description: "Manage allow, ask, and deny rules for tools", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/plan", description: "Switch into plan mode; optionally seed a description", takesArg: true, argHint: "[description]", common: false, dangerous: false },
  { command: "/plugin", description: "Manage plugins — list, install, enable, or disable", takesArg: true, argHint: "[subcommand]", common: false, dangerous: false },
  { command: "/recap", description: "Generate a one-line summary of the current session", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/release-notes", description: "View the changelog in a version picker", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/rename", description: "Rename the current session", takesArg: true, argHint: "[name]", common: false, dangerous: false },
  { command: "/rewind", description: "Roll back code and conversation to a checkpoint", takesArg: false, argHint: "", common: false, dangerous: true },
  { command: "/security-review", description: "Analyze pending changes for security vulnerabilities", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/simplify", description: "Review changed code for cleanups and apply fixes", takesArg: true, argHint: "[target]", common: false, dangerous: false },
  { command: "/skills", description: "List available skills and toggle their visibility", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/statusline", description: "Configure the shell status line display", takesArg: true, argHint: "[description]", common: false, dangerous: false },
  { command: "/tasks", description: "View and manage background tasks for this session", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/terminal-setup", description: "Configure terminal keybindings (e.g. Shift+Enter)", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/theme", description: "Change the color theme", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/vim", description: "Toggle Vim editing mode for the prompt", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/exit", description: "Exit the CLI (detaches if attached to a background session)", takesArg: false, argHint: "", common: false, dangerous: true },
];
