import { Download, Copy, ExternalLink, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useBlocker, useLocation, useNavigate } from "react-router";
import { open, openAncestors, noteDeletedFile } from "@/lib/files-tree";
import { useLoaderData, useRouteLoaderData } from "react-router";
import { useBack } from "@/hooks/use-back";
import { AppHeader } from "@/components/app-header";
import { filesPath } from "@/lib/nav";
import { downloadFileUrl, openFileUrl, deleteFile, saveFile } from "@/lib/api";
import { ROOT_ROUTE_ID, type FilesData, type HomeData } from "@/lib/loaders";
import { FilesTree, FileSearchResults, useFileSearch } from "@/components/files-tree";
import { baseName } from "@/lib/format";
import { useDesktop } from "@/lib/desktop";
import { FilesGit } from "@/components/files-git";
import { isReadOnly } from "@/lib/types";
import { setStatus } from "@/lib/status";
import { usePendingConfirm } from "@/hooks/use-pending-confirm";
import { DestructiveActionRow } from "@/components/action-sheet-rows";
import { StatusArea } from "@/components/status-area";
import { MarkdownText } from "@/components/markdown-text";

export function FilesRoute() {
  const loaded = useLoaderData() as FilesData; const home = useRouteLoaderData(ROOT_ROUTE_ID) as HomeData;
  const desktop = useDesktop().on; const search = useFileSearch(); const goBack = useBack(filesPath()); const backGuard = useRef<(() => boolean) | null>(null); const panes = [...home.agents, ...home.shellPanes];
  const [gitFocus, setGitFocus] = useState(""); useEffect(() => { setGitFocus(loaded.rel); }, [loaded.rel]);
  useEffect(() => { if (loaded.rel) { openAncestors(loaded.rel); if (loaded.data?.kind === "dir") open(loaded.rel); } }, [loaded.rel, loaded.data?.kind]);
  const gitPath = desktop ? loaded.rel : (loaded.rel || gitFocus);
  if (loaded.error || !loaded.data) return <div className="flex flex-1 items-center justify-center p-6 text-muted-foreground">{loaded.rel ? "Not found" : "Files isn't turned on — set SIGHTR_WORK_ROOT on the host"}</div>;
  const data = loaded.data;
  const content = data.kind === "file" ? <FileDetail data={data} readOnly={isReadOnly(home.device)} backGuard={backGuard} goBack={goBack} /> : <div className="flex flex-1 flex-col"><FilesGit path={loaded.rel} panes={panes} /><div className="flex flex-1 items-center justify-center text-muted-foreground">Pick a file</div></div>;
  if (desktop) return <div className="mx-auto flex min-h-0 w-full flex-1 flex-col"><AppHeader bridge={home.bridge} error={home.error} wordmark={false}><span className="truncate font-semibold">{loaded.rel ? baseName(loaded.rel) : "Files"}</span></AppHeader>{content}<div className="pointer-events-none fixed inset-x-0 bottom-0 z-30 mx-auto w-full max-w-screen-sm px-3 pb-[calc(env(safe-area-inset-bottom)_+_4rem)]"><StatusArea /></div></div>;
  return <div className="mx-auto flex min-h-0 w-full max-w-screen-sm flex-1 flex-col"><AppHeader bridge={home.bridge} error={home.error} wordmark={false} onBack={loaded.rel ? () => { if (!(backGuard.current?.() ?? false)) goBack(); } : undefined}><span className="truncate font-semibold">{loaded.rel ? baseName(loaded.rel) : "Files"}</span></AppHeader><div className="p-3"><input type="search" value={search.query} onChange={(e) => search.setQuery(e.target.value)} placeholder="Find files" inputMode="search" autoCapitalize="off" autoCorrect="off" className="w-full rounded border bg-background px-3 py-2" /></div>{search.results ? <div className="min-h-0 flex-1 overflow-y-auto"><FileSearchResults results={search.results} onPick={search.clear} /></div> : data.kind === "dir" ? <div className="min-h-0 flex-1 overflow-y-auto"><FilesGit path={gitPath} panes={panes} /><FilesTree root={loaded.rel === "" ? data : undefined} selected={loaded.rel} onFolderSelect={setGitFocus} /></div> : content}<div className="pointer-events-none fixed inset-x-0 bottom-0 z-30 mx-auto w-full max-w-screen-sm px-3 pb-[calc(env(safe-area-inset-bottom)_+_4rem)]"><StatusArea /></div></div>;
}
function FileDetail({ data, readOnly, backGuard, goBack }: { data: Extract<FilesData["data"], { kind: "file" }>; readOnly: boolean; backGuard: { current: (() => boolean) | null }; goBack?: () => void }) {
  const navigate = useNavigate(); const location = useLocation(); const { confirm, pending } = usePendingConfirm();
  const desktop = useDesktop().on; const [deleting, setDeleting] = useState(false); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(data.text ?? "");
  const [saved, setSaved] = useState({ text: data.text ?? "", mtimeMs: data.mtimeMs, size: data.size }); const [saving, setSaving] = useState(false); const saveGen = useRef(0); const [copied, setCopied] = useState(false); const [pendingBack, setPendingBack] = useState(false);
  useEffect(() => { backGuard.current = null; setEditing(false); setPendingBack(false); setSaving(false); saveGen.current += 1; const lf = (data.text ?? "").replace(/\r\n/g, "\n"); setDraft(lf); setSaved({ text: lf, mtimeMs: data.mtimeMs, size: data.size }); /* eslint-disable-next-line react-hooks/exhaustive-deps -- path/search is a new file (or session). Same-URL loader refresh must not clobber a dirty buffer. */ return () => { backGuard.current = null; }; }, [data.path, location.search]);
  const dirty = editing && draft !== saved.text; const bypass = useRef(false); const blocker = useBlocker(({ currentLocation, nextLocation }) => dirty && !bypass.current && (currentLocation.pathname !== nextLocation.pathname || currentLocation.search !== nextLocation.search));
  backGuard.current = () => { if (!dirty) return false; setPendingBack(true); return true; };
  useEffect(() => { bypass.current = false; }, [location.key]);
  useEffect(() => { if (!dirty) return; const onBeforeUnload = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ""; }; window.addEventListener("beforeunload", onBeforeUnload); return () => window.removeEventListener("beforeunload", onBeforeUnload); }, [dirty]);
  async function onDelete() { if (deleting || !confirm(`delete:${data.path}`)) return; setDeleting(true); try { const res = await deleteFile(data.path); if (res.ok) { noteDeletedFile(data.path); navigate(filesPath(), { replace: true }); } else setStatus(res.error ?? "Delete failed", "error"); } catch (e) { setStatus(e instanceof Error ? e.message : String(e), "error"); } finally { setDeleting(false); } }
  async function onSave() { if (saving || !dirty) return; const gen = ++saveGen.current; setSaving(true); try { const res = await saveFile(data.path, draft, saved.mtimeMs); if (gen !== saveGen.current) return; if (res.ok) { setSaved({ text: draft, mtimeMs: res.mtimeMs, size: res.size }); setEditing(false); setStatus("Saved", "success"); } else if (res.error === "file changed") setStatus("File changed on disk — not saved", "error"); else setStatus(res.error ?? "Save failed", "error"); } catch (e) { if (gen === saveGen.current) setStatus(e instanceof Error ? e.message : String(e), "error"); } finally { if (gen === saveGen.current) setSaving(false); } }
  function onDiscard() { if (saving) return; saveGen.current += 1; setDraft(saved.text); setEditing(false); }
  const src = openFileUrl(data.path); const copy = async () => { try { await navigator.clipboard.writeText(data.path); } catch { const t = document.createElement("textarea"); t.value = data.path; document.body.appendChild(t); t.select(); document.execCommand("copy"); t.remove(); } setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <div className={desktop && editing ? "flex min-h-0 flex-1 flex-col overflow-auto p-3" : "flex-1 overflow-auto p-3"}><div className={editing ? "sticky top-0 z-10 mb-3 bg-background pb-2" : "mb-3"}>{(blocker.state === "blocked" || pendingBack) ? <div className="flex flex-wrap items-center gap-2"><span className="text-sm">Unsaved edits</span><button type="button" className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={() => { setPendingBack(false); if (blocker.state === "blocked") blocker.reset(); }}>Stay</button><button type="button" className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={() => { saveGen.current += 1; if (blocker.state === "blocked") blocker.proceed(); else { bypass.current = true; onDiscard(); setPendingBack(false); goBack?.(); } }}>Discard edits</button></div> : <><div className="flex flex-wrap gap-2">{data.openInBrowser && <a className="rounded bg-primary px-3 py-2 text-primary-foreground" href={src} target="_blank" rel="noopener noreferrer"><ExternalLink className="mr-1 inline size-4" />Open in browser</a>}<button className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={copy}><Copy className="mr-1 inline size-4" />{copied ? "Copied" : "Copy path"}</button><a className="rounded bg-primary px-3 py-2 text-primary-foreground" href={downloadFileUrl(data.path)} download={data.name}><Download className="mr-1 inline size-4" />Download</a>{editing && <><button type="button" className="rounded bg-primary px-3 py-2 text-primary-foreground" disabled={!dirty || saving} onClick={() => void onSave()}>{saving ? "Saving…" : "Save"}</button><button type="button" className="rounded bg-primary px-3 py-2 text-primary-foreground" disabled={saving} onClick={onDiscard}>Discard</button></>}{!editing && data.binary === false && data.truncated !== true && !readOnly && <button type="button" className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={() => { setEditing(true); setDraft(saved.text); }}>Edit</button>}</div>{data.binary === false && !readOnly && !editing && <div className="border-t pt-2"><DestructiveActionRow icon={<Trash2 className="size-4" />} label="Delete" confirmLabel={`Really delete ${data.name}?`} closingLabel="Deleting…" armed={pending === `delete:${data.path}`} closing={deleting} onClick={onDelete} /></div>}</>}</div>{editing ? <textarea value={draft} onChange={(e) => setDraft(e.target.value)} autoCapitalize="none" autoCorrect="off" autoComplete="off" spellCheck={false} onKeyDown={(e) => { if ((e.ctrlKey || e.metaKey) && !e.altKey && (e.key === "s" || e.key === "S")) { e.preventDefault(); if (dirty && !saving) void onSave(); } }} className={(desktop ? "min-h-0 flex-1 resize-none" : "min-h-[30dvh] max-h-[40dvh]") + " w-full whitespace-pre-wrap break-words font-mono text-sm rounded border bg-background p-2"} /> : <FilePreview data={{ ...data, text: saved.text, size: saved.size }} src={src} />}</div>;
}
function FilePreview({ data, src }: { data: Extract<FilesData["data"], { kind: "file" }>; src: string }) { if (data.embed === "image") return <img src={src} alt={data.name} className="max-h-[70dvh] max-w-full object-contain" />; if (data.embed === "video") return <video src={src} controls playsInline preload="metadata" className="max-h-[70dvh] w-full bg-black" />; if (data.embed === "audio") return <audio src={src} controls preload="metadata" className="w-full" />; if (data.binary) return <p className="text-muted-foreground">{data.openInBrowser ? "Can't preview this file here — open it in the browser or download it" : "Can't preview this file — download it instead"}</p>; const note = data.truncated && <p className="text-xs text-muted-foreground">truncated at 512 KB</p>; if (/.(md|markdown)$/i.test(data.name)) return <><MarkdownText text={data.text ?? ""} />{note}</>; return <><pre className="whitespace-pre-wrap break-words font-mono text-sm">{data.text}</pre>{data.truncated && <p className="text-xs text-muted-foreground">truncated at 512 KB</p>}</>; }
