import { GitBranch } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import { fetchFolderGit } from "@/lib/api";
import { DiffView } from "./diff-view";
import { panePath } from "@/lib/nav";
import { paneDisplayName, STATUS_LABEL, type AgentView, type FolderGitResponse } from "@/lib/types";

export function FilesGit({ path, panes }: { path: string; panes: AgentView[] }) {
  const navigate = useNavigate(); const [open, setOpen] = useState(false); const [result, setResult] = useState<FolderGitResponse | null>(null); const [loading, setLoading] = useState(false); const [refreshes, setRefreshes] = useState(0); const paneKey = panes.map((p) => p.paneId).join(",");
  useEffect(() => { setResult(null); }, [path]);
  useEffect(() => { if (!open) return; const controller = new AbortController(); setLoading(true); fetchFolderGit(path, panes.map((p) => p.paneId), controller.signal).then(setResult).catch((e) => { if (e.name !== "AbortError") setResult(null); }).finally(() => setLoading(false)); return () => controller.abort(); }, [open, path, paneKey, refreshes]);
  const refresh = () => { setResult(null); setRefreshes((n) => n + 1); };
  return <section className="border-b p-3"><button type="button" className="flex w-full items-center gap-2 text-left font-semibold" onClick={() => setOpen((v) => !v)}><GitBranch className="size-4" />Git <span className="font-normal text-muted-foreground">{path === "" ? "Files root" : path}</span></button>{open && <div className="mt-3 space-y-2 text-sm">{loading ? <p className="text-muted-foreground">Checking…</p> : !result ? <p className="text-muted-foreground">Couldn't read git here</p> : !result.available ? <p>{{ "outside-root": "This folder is outside the Files root", "not-a-repo": "Not a git repo — this folder isn't inside a checkout. Browse into one and open Git there.", "git-unavailable": "git isn't installed on the host", timeout: "git took too long" }[result.reason]}</p> : <><p className="text-muted-foreground">{result.branch ?? (result.detached ? "detached HEAD" : "no commits yet")} · {result.repo}{result.rel && `/${result.rel}`}</p>{result.clean ? <p>Working tree clean</p> : <div>{result.entries.map((e) => <div className="flex gap-3" key={e.path}><code>{e.x}{e.y}</code><span>{e.path}</span></div>)}</div>}{result.hidden > 0 && <p>{result.hidden} hidden file{result.hidden === 1 ? "" : "s"} not shown</p>}{result.statusTruncated && <p>first 500 changes shown</p>}{(() => { const inRepo = result.panes.map((id) => panes.find((p) => p.paneId === id)).filter(Boolean) as AgentView[]; return inRepo.length ? <div aria-label="Panes in this repo" className="flex gap-2 overflow-x-auto">{inRepo.map((pane) => <button type="button" className="shrink-0 rounded border px-2 py-1" key={pane.paneId} onClick={() => navigate(panePath(pane.paneId))}>{paneDisplayName(pane)} <span className="text-muted-foreground">{STATUS_LABEL[pane.status]}</span></button>)}</div> : <p>No panes in this repo</p>; })()}{result.diff && <DiffView diff={result.diff} />}{result.diffTruncated && <p>diff truncated</p>}{result.noCommits && <p>no commits yet — nothing to diff against</p>}<button type="button" onClick={refresh}>Refresh</button></>}</div>}</section>;
}
